name: Format Code

on:
  pull_request:
  
  workflow_dispatch:

jobs:
  format-dart:
    name: Format Dart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
          
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.3
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/linux

      - name: Format
        run: flutter format lib/* test/*

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply dart formatting changes
          file_pattern: lib/* test/*
