name: Format Code

on:
  pull_request:
  
  workflow_dispatch:

jobs:
  format-dart:
    name: Format Dart
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.5
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/linux

      - name: Format
        run: flutter format lib/* test/*

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply dart formatting changes
          branch: ${{ github.head_ref }}
          file_pattern: lib/* test/*
