name: Run Tests

on:
  push:
    branches: [main]

  pull_request:
  
  workflow_dispatch:

jobs:
  flutter-tests:
    name: Flutter Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.5
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/linux

      - name: Get dependencies
        run: flutter pub get
        
      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
  
  pplib_tests:
    name: PathPlannerLib Tests
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./pathplannerlib
        
      - name: Compile and run tests
        run: ./gradlew build -PreleaseMode
        working-directory: ./pathplannerlib
